#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        echo "Removing Bitwarden CLI..."
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
